### ISSUE TITLE
requisitos funcionais

### ISSUE THREAD

**Issue by Ricardoan** [Marinofull/relatoriolatec#1]

**Comment by Ricardoan** [comment]
Definição de requisitos de usuário
Nesta seção são descritos os requisitos funcionais, os quais correspondem as ações que poderão ser executadas no software, e os requisitos não funcionais, os quais correspondem ao conjunto de restrições relacionado ao modo de funcionamento do software.
Os requisitos são classificados em três categorias de prioridade, são elas:
• Essencial – para os requisitos que devem ser implementados impreterivelmente, sem o conjunto de requisitos essenciais o software não poderia ser utilizado;
• Importante – para os requisitos que devem ser implementados para que se obtenha um bom aproveitamento do produto de software;
• Desejável – para os requisitos que se não forem implementados não comprometerão o uso adequado do software.


REQUISITOS FUNCIONAIS:
Cadastro de usuário: (Comum e Administrador)
Cadastramento de dados pessoais do cliente
O sistema possibilita a geração de relatório gerências
Continuar pois não conseguir acessar o repositório !!!




Requisitos não funcionais:
Requisitos não funcionais são relacionados ao uso da aplicação em termos de desempenho, usabilidade, confiabilidade, disponibilidade, segurança e tecnologias envolvidas:
Com o crescente número de usuários vindos de dispositivos móveis, requisitos não funcionais como portabilidade e mobilidade tornam-se fundamentais em praticamente todos os sistemas web. Além deles, a preocupação com interoperabilidade, localização geográfica e alta disponibilidade também fazem parte do mapeamento e desenvolvimento de requisitos não funcionais.
Seguem os requisitos não funcionais do sistema:
•	Performance: O PAgFrame proporciona uma boa performance no auxílio para a criação das páginas, visto que, o sistema pode criar n requisições de página em um espaço curto de tempo
•	Confiabilidade: O sistema tem alta disponibilidade, em torno de 99% do tempo. As estruturas das páginas da internet são criadas em tempo real.
•	Portabilidade: O sistema foi projetado para rodar em qualquer plataforma.
•	Requisitos de entrega: O sistema gera um relatório informando o que já foi feito na criação da pagina de internet e quanto ainda falta para ser finalizados. Os dados são demonstrados em porcentagem.  
•	Requisitos éticos: O sistema não apresentará aos usuários quaisquer dados de cunho privativo.
•	Legalidade: o sistema deverá atender às normas legais, tais como padrões, leis, etc.
•	Integração: O sistema integra com outra aplicação
•	Disponibilidade: ("O sistema estará disponível pelo menos 99,7% do tempo em dias de semana entre 08:00 até as 18:00 e pelo menos 99,95% entre 12:00 e 13:00")

**Comment by niltonvasques** [comment]
?

**Comment by Marinofull** [comment]
:+1:

**Comment by Marinofull** [comment]
zoha niuma

**Comment by Ricardoan** [comment]
Que foi  ????

Me explique um pouco do sistema?
Além da tela de cadastro de usuários, quais as outras tela do sistema??? Sem esses dados não da pra fazer os requisitos funcionais de sistemas, além do mais, o arquivo pdf que vc envio não continha a informação

Date: Thu, 30 Apr 2015 09:52:24 -0700

**Comment by Marinofull** [comment]
Como eu falei por email vc olhava as issues (no link que mandei) pra entender melhor.
a versão atual do pdf se encontrará sempre aqui https://github.com/Marinofull/relatoriolatec
a versão atual é esta: https://github.com/Marinofull/relatoriolatec/blob/master/sbc-template.pdf

Reenvio os links da issues:
https://github.com/Marinofull/trabalhoLabWeb/issues
